services:
  samfm-app:
    build: .
    container_name: samfm-app
    ports:
      - "5000:${PORT}"
    restart: always
    volumes:
      - ./samfm_data:/app/public/user-uploads # retain public data on disk
      #- /etc/letsencrypt/live/soundcamp.radio/fullchain.pem:/app/certificates/fullchain.pem
      #- /etc/letsencrypt/live/soundcamp.radio/privkey.pem:/app/certificates/privkey.pem
networks:
  default:
    name: main-network
    external: true